name: Front analyze
# execute on git push
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  back_CI:
    # execute on the following environment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "front"
    strategy:
      matrix:
        node: ['20.x']

    name: Build Angular with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Run front test
        run: npm test --watch=false --browsers ChromeHeadless
      
      - name: Run front project
        run: npm run build