name: Front analyze
# execute on git push
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  front_ci:
    # execute on the following environment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "front"
    strategy:
      matrix:
        node: ['20.x']

    name: Build Angular with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Run front test
        run: npm test -- --watch=false --browsers=ChromeHeadless
      
      - name: Run front project
        run: npm run build
  
  docker-ci:
    name: Docker CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:latest