name: Test back-end

on: main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "back"
    strategy:
      matrix:
        java: [11]
    name: Run unit tests on Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn -f pom.xml clean test
